### ISSUE TITLE
Doesn't recognise variables 

### ISSUE THREAD

**Issue by thanos-cfd** [blendernc/blendernc#100]
I tried the blendernc plugin with a NetCDF file from ECMWF but cant read the variables. Its a NetCDF4 data model with a HDF5 file format. It worked though the plugin with the .nc file inside /tests/dataset/. Any way to output errors, or debug why it doesnt work? thanks!

**Comment by josuemtzmo** [comment]
@thanos-cfd Could you please provide a screenshot or copy the error output? Otherwise, I can't really provide much information on why it's failing. Also, can you attach the header of the netCDF file you are trying?

**Comment by thanos-cfd** [comment]
Hi Jose, thanks for prompt response - please see below the error output:    
```
    long_name_list = [ncdata[var].attrs["long_name"] for var in variables]                                              
    KeyError: 'long_name'         
```                        

And the header of the netCDF file:
```
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5): 
     CDI: Climate Data Interface version 1.9.5 (http://mpimet.mpg.de/cdi) 
     Conventions: CF-1.6  
     institution: European Centre for Medium-Range Weather Forecasts   
     CDO: Climate Data Operators version 1.9.5 (http://mpimet.mpg.de/cdo)   
     cdo_openmp_thread_number: 8  
     history: Sun Jan  3 00:02:27 2021: ncatted -a _FillValue,mrt,c,f,-9.0e33 ECMWF_mrt_20201231_v1.0_int.tmp ECMWF_mrt_20201231_v1.0_int.nc 
Sun Jan 03 00:02:24 2021: cdo -P 8 -z zip_1 -R -f nc4 -addc,273.15 -setname,mrt -remapnn,lsm.nc mrt.20201231.grib ECMWF_mrt_20201231_v1.0_int.tmp 
    NCO: netCDF Operators version 4.7.8 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)   
    dimensions(sizes): time(24), lon(1440), lat(601) 
    variables(dimensions): float64 time(time), float64 lon(lon), float64 lat(lat), float32 mrt(time, lat, lon) 
    groups:  
```
 
Hope this helps.

**Comment by josuemtzmo** [comment]
@thanos-cfd, thanks for raising this issue, BlenderNC expects data with a long_name according to the standard way of storing netCDFs. However, after you pointed this out, there was I think a simple solution to it (I haven't tested this, as I currently don't have a netCDF at hand without long_name attributes). I've changed the code in the [dev](https://github.com/blendernc/blendernc/tree/dev) branch.

You can download the latest dev branch installable from: 
https://github.com/blendernc/blendernc-zip-install/raw/dev/blendernc.zip
Optionally, you could update from within blender to the dev branch following the instructions:
https://blendernc.readthedocs.io/en/latest/install.html#update-blendernc

The next release of BlenderNC will contain this fix.

**Comment by thanos-cfd** [comment]
@josuemtzmo that did the trick, awesome work - thanks so much!
