### ISSUE TITLE
Exclude doc folder from trigger python code tests via CI

### ISSUE THREAD

**Issue by whatnick** [blendernc/blendernc#111]
Python code tests take around 15 minutes and slow down merging of small docs PR's. They are also unnecessary for pure documentation changes. Allow skipping python code tests when changes are only in docs folder.

Possibly also use this : https://github.com/marketplace/actions/skip-duplicate-actions to skip unnecessary CI runs on commit + PR merge etc.

**Comment by josuemtzmo** [comment]
I've implemented this, thanks for the link!
