### ISSUE TITLE
Problem when opening netcdf file

### ISSUE THREAD

**Issue by thomasarsouze** [blendernc/blendernc#118]
Hi,

thanks for developing this tools. I have an issue when trying to reproduce the most simple exemple with gebco topography.
OS: MacOS Catalina 10.15.7
Blender: v2.93.1
Blendernc: 0.4.0
python: 
```
./python3.9 -m pip
list
Package         Version
--------------- ---------
certifi         2020.12.5
cftime          1.5.0
chardet         4.0.0
cloudpickle     1.6.0
cmocean         2.0
cycler          0.10.0
Cython          0.29.21
dask            2021.7.0
docrep          0.2.7
fsspec          2021.7.0
future          0.18.2
idna            2.10
kiwisolver      1.3.1
locket          0.2.1
matplotlib      3.4.2
netCDF4         1.5.7
numpy           1.19.5
pandas          1.3.0
partd           1.2.0
Pillow          8.3.1
pip             20.2.3
pyparsing       2.4.7
python-dateutil 2.8.2
pytz            2021.1
PyYAML          5.4.1
requests        2.25.1
scipy           1.7.0
setuptools      49.2.1
six             1.16.0
toolz           0.11.1
urllib3         1.26.3
xarray          0.18.2
xgcm            0.5.2
```

When I try to do the "Apply Material" with the `elevation` variable of the gebco file, I get  the following error.

```
Python: Traceback (most recent call last):
  File "/Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/operators.py", line 334, in execute
    blendernc_material.node_tree.links.new(cmap.inputs[0], imagetex.outputs[0])
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1
```

Any idea what might be wrong ?

Thx.
Thomas.

**Comment by whatnick** [comment]
Is it possible to share the source NetCDF or a link to it ? We can try it out. Did you create the UV sphere onto which this displacement texture will be applied ?

**Comment by josuemtzmo** [comment]
@thomasarsouze, I haven't been able to reproduce the error, we may need more information to figure out what is happening. Could you send us the header of the netCDF? and could you send us a screenshot of the shader editor of the "BlenderNC_default" material? (see image below)

This is an issue when assigning the material to the object that you have selected. In particular, when trying to connect the colormap to the image texture nodes in the shader editor. You could fix this by manually linking the nodes. 

Were you using an older version of BlenderNC before? Note that we updated the API function naming, so If you were using a version of BlenderNC < 0.4.0, many nodes became undefined and that could be the reason why the Blender is not finding the node, if that's the case when you open the shader editor, you will see a colormap node without input, nor outputs.  

<img width="893" alt="Screen Shot 2021-07-24 at 12 23 01 pm" src="https://user-images.githubusercontent.com/9144063/126854880-8d68acfd-6f3c-47f0-b82d-a6edd6c681d3.png">

**Comment by thomasarsouze** [comment]
Thx both of you for the quick first answers.
1) I downloaded the last version of Blender on my Mac and followed this [installation page](https://blendernc.readthedocs.io/en/latest/install.html) using the pip method
2) I followed the [GEBCO example](https://blendernc.readthedocs.io/en/latest/examples/import_gebco_netCDF.html) and downloaded on the offical page the GEBCO_2020.nc file
3) I can load the file, select the variable, delte the cube, create the sphere, select the sphere but then the error comes when I try to apply the material.

Tis is the first time I'm using BlenderNC, no previous version installed.

Also you can find the screen shot of the Blender NC_default and indeed it seems it doesn't do the links.

Header of the netcdf file:
```
ncdump -h GEBCO_2020.nc
netcdf GEBCO_2020 {
dimensions:
	lon = 86400 ;
	lat = 43200 ;
variables:
	double lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:sdn_parameter_urn = "SDN:P01::ALONZZ01" ;
		lon:sdn_parameter_name = "Longitude east" ;
		lon:sdn_uom_urn = "SDN:P06::DEGE" ;
		lon:sdn_uom_name = "Degrees east" ;
	double lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
		lat:sdn_parameter_urn = "SDN:P01::ALATZZ01" ;
		lat:sdn_parameter_name = "Latitude north" ;
		lat:sdn_uom_urn = "SDN:P06::DEGN" ;
		lat:sdn_uom_name = "Degrees north" ;
	short elevation(lat, lon) ;
		elevation:standard_name = "height_above_reference_ellipsoid" ;
		elevation:long_name = "Elevation relative to sea level" ;
		elevation:units = "m" ;
		elevation:sdn_parameter_urn = "SDN:P01::BATHHGHT" ;
		elevation:sdn_parameter_name = "Sea floor height (above mean sea level) {bathymetric height}" ;
		elevation:sdn_uom_urn = "SDN:P06::ULAA" ;
		elevation:sdn_uom_name = "Metres" ;

// global attributes:
		:Conventions = "CF-1.6" ;
		:title = "The GEBCO_2020 Grid - a continuous terrain model for oceans and land at 15 arc-second intervals" ;
		:institution = "On behalf of the General Bathymetric Chart of the Oceans (GEBCO), the data are held at the British Oceanographic Data Centre (BODC)." ;
		:source = "The GEBCO_2020 Grid is the latest global bathymetric product released by the General Bathymetric Chart of the Oceans (GEBCO) and has been developed through the Nippon Foundation-GEBCO Seabed 2030 Project. This is a collaborative project between the Nippon Foundation of Japan and GEBCO. The Seabed 2030 Project aims to bring together all available bathymetric data to produce the definitive map of the world ocean floor and make it available to all." ;
		:history = "Information on the development of the data set and the source data sets included in the grid can be found in the data set documentation available from https://www.gebco.net" ;
		:references = "DOI: 10.5285/a29c5465-b138-234d-e053-6c86abc040b9" ;
		:comment = "The data in the GEBCO_2020 Grid should not be used for navigation or any purpose relating to safety at sea." ;
		:node_offset = 1. ;
}
```
[Capture d’écran 2021-07-24 à 16.24.22.pdf](https://github.com/blendernc/blendernc/files/6872578/Capture.d.ecran.2021-07-24.a.16.24.22.pdf)

**Comment by josuemtzmo** [comment]
@thomasarsouze, I've continued trying to replicate this issue, and so far, I can't find the issue. After looking at the screenshot you sent, I think the issue has to do with the installation of the modules, as no image has been attached to the `Texture image` node. In order to debug this, could you run Blender from the terminal and copy-paste the error or errors here. You can run Blender from the terminal by doing something like:

```
/Applications/Blender_2.93.app/Contents/MacOS/Blender
```
or 
```
/Applications/Blender.app/Contents/MacOS/Blender
```

I've tested BlenderNC using French, which is the only obvious difference atm, and it works 🤔. Anyhow, to make sure that blenderNC imported the NetCDF and loaded the image, can you also send me a screenshot of the Image editor, image `BlenderNC_default`, and BlenderNC NodeTree? (See attached screenshots)

- Image:
<img width="1387" alt="Screen Shot 2021-07-25 at 5 26 32 pm" src="https://user-images.githubusercontent.com/9144063/126891333-8cedd9b7-0334-498e-bcd3-146b43141aba.png">
- NodeTree follow this [tutorial to find the BlenderNC NodeTree](https://blendernc.readthedocs.io/en/latest/pro_mode.html):
<img width="1386" alt="Screen Shot 2021-07-25 at 5 30 37 pm" src="https://user-images.githubusercontent.com/9144063/126891393-6f18ff01-5cb4-42ab-8462-12757bde565f.png">

**Comment by josuemtzmo** [comment]
Could you try reinstalling the required modules?

**Comment by thomasarsouze** [comment]
Hi ,

Here is the log of the app when launched from the terminal.
It looks that I have a backend error when launching cmocean (same error when launching cmocean in a python terminal, however, I don't have this error with python installed in other environment).

```
blendernc addon: Verbose is enabled
blendernc addon: Read in JSON settings from file
Registering to Change Defaults
Info: Deleted 1 object(s)

Attempting to load ('/Users/arsouze/Nextcloud/gebco_2020_netcdf/GEBCO_2020', '.nc') format files
Info: Lazy load of /Users/arsouze/Nextcloud/gebco_2020_netcdf/GEBCO_2020.nc!
Attempting to load ('/Users/arsouze/Nextcloud/gebco_2020_netcdf/GEBCO_2020', '.nc') format files
Info: Lazy load of /Users/arsouze/Nextcloud/gebco_2020_netcdf/GEBCO_2020.nc!
/Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/image.py:72: RuntimeWarning: invalid value encountered in true_divide
  return (data - min_range) / var_range
--------------------------------------------------------------------------------------
| Variable load || Image dimensions || Load Frame || Assign to pixel || Update Image |
|      5.89e-05 ||         4.24e-03 ||   1.64e-01 ||        3.60e-05 ||     5.96e-06 |
--------------------------------------------------------------------------------------
| Total =                                                           1.69e-01 seconds |
| FPS =                                                                          5.9 |
| Frame =                                                                          0 |
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
| Variable load || Image dimensions || Load Frame || Assign to pixel || Update Image |
|      5.51e-05 ||         4.84e-03 ||   7.34e-05 ||        1.31e-05 ||     4.05e-06 |
--------------------------------------------------------------------------------------
| Total =                                                           5.02e-03 seconds |
| FPS =                                                                        2e+02 |
| Frame =                                                                          0 |
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
| Variable load || Image dimensions || Load Frame || Assign to pixel || Update Image |
|      4.91e-05 ||         2.84e-02 ||   1.29e+00 ||        4.55e-03 ||     9.78e-06 |
--------------------------------------------------------------------------------------
| Total =                                                           1.33e+00 seconds |
| FPS =                                                                         0.75 |
| Frame =                                                                          1 |
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
| Variable load || Image dimensions || Load Frame || Assign to pixel || Update Image |
|      3.00e-05 ||         4.24e-02 ||   1.77e+00 ||        4.39e-03 ||     1.00e-05 |
--------------------------------------------------------------------------------------
| Total =                                                           1.82e+00 seconds |
| FPS =                                                                         0.55 |
| Frame =                                                                          1 |
--------------------------------------------------------------------------------------

Python: Traceback (most recent call last):
  File "/Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/nodes/cmaps/cmapsnode.py", line 204, in init
    self.colormaps = default_colorramp()
  File "/Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/nodes/cmaps/cmapsnode.py", line 89, in default_colorramp
    colormaps = core_colorramp.get_cmaps()
  File "/Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/nodes/cmaps/utils_colorramp.py", line 146, in get_cmaps
    cmap = importlib.import_module(maps)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/cmocean/__init__.py", line 11, in <module>
    from . import cm, tools, data
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/cmocean/data.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/matplotlib/pyplot.py", line 277, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/matplotlib/pyplot.py", line 278, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/matplotlib/backends/_backend_tk.py", line 7, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

location: /Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/operators.py:304
Python: Traceback (most recent call last):
  File "/Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/operators.py", line 334, in execute
    blendernc_material.node_tree.links.new(cmap.inputs[0], imagetex.outputs[0])
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1
Erreur: Python: Traceback (most recent call last):
  File "/Users/arsouze/Library/Application Support/Blender/2.93/scripts/addons/blendernc/operators.py", line 334, in execute
    blendernc_material.node_tree.links.new(cmap.inputs[0], imagetex.outputs[0])
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1
```

**Comment by thomasarsouze** [comment]
As for loading the netcdf file, it looks fine.
[Capture d’écran 2021-07-26 à 11.23.11.pdf](https://github.com/blendernc/blendernc/files/6877085/Capture.d.ecran.2021-07-26.a.11.23.11.pdf)
[Capture d’écran 2021-07-26 à 11.22.39.pdf](https://github.com/blendernc/blendernc/files/6877088/Capture.d.ecran.2021-07-26.a.11.22.39.pdf)

**Comment by josuemtzmo** [comment]
Do you get the same error if you import `import matplotlib.pyplot as plt` in the **Blender** terminal? if so, you will need to install tkinter. 

What is the output of the following command?

```
import matplotlib
matplotlib.get_backend()
```
If the output is:
> tkagg
your installation is using the `tkagg` backend which requires tkinter. I'm not sure how to fix this yet, but it seems something went wrong with your installation, and instead of using the default backend for macOS in `matplotlib`; `macosx`, your installation is using `tkagg`. 

Did you get any error if you run the following lines in the  **Blender**  terminal (*A pop-up plot should show up):
```
import matplotlib
matplotlib.use('MACOSX') 
```

**Comment by thomasarsouze** [comment]
OK. You're right, matplotlib was using the wrong default backend. I had to change manualy this in ~/.matplotlib/matplotlibrc and it now works like a charm.

Thanks a lot for your quick and helpfull answers.

Closing this ticket.

**Comment by StephenEdmundson7** [comment]
I have the same issue but instead of tkagg I have just 'agg' - any suggestions?

**Comment by josuemtzmo** [comment]
Can you add here the error message?

**Comment by StephenEdmundson7** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/61392401/173241904-a59b44b1-1387-45c4-8ad4-2a870580a585.png">


This is the error message

**Comment by markusritschel** [comment]
I'm having exactly the same error. 
OS: Linux KDE neon ("jammy")
Blender v3.3

**Comment by josuemtzmo** [comment]
Have you tried this? if so, what's the output?

> Thanks for sending all the information! Now I have a better idea of the issue.
> 
> The issue seems to be with `matplotlib` rather than `cmocean`. Do you get the same error if you import `import matplotlib.pyplot as plt` in the **Blender** terminal? if so, you will need to install tkinter.
> 
> What is the output of the following command?
> 
> ```
> import matplotlib
> matplotlib.get_backend()
> ```
> 
> If the output is:
> 
> > tkagg
> 
> your installation is using the `tkagg` backend which requires tkinter. I'm not sure how to fix this yet, but it seems something went wrong with your installation, and instead of using the default backend for macOS in `matplotlib`; `macosx`, your installation is using `tkagg`.
> 
> Did you get any error if you run the following lines in the **Blender** terminal (*A pop-up plot should show up):
> 
> ```
> import matplotlib
> matplotlib.use('MACOSX') 
> ```
