### ISSUE TITLE
BlenderNC in Blender 3.0

### ISSUE THREAD

**Issue by josuemtzmo** [blendernc/blendernc#125]
This issue will keep track of support for blenderNC in Blender 3.0:

**Comment by josuemtzmo** [comment]
As of 25th of July, BlenderNC works in Blender 3.0:

<img width="556" alt="Screen Shot 2021-07-25 at 6 30 52 pm" src="https://user-images.githubusercontent.com/9144063/126892894-5ab02612-a523-499c-84de-55cd6b542321.png">

**Comment by josuemtzmo** [comment]
As of 30th of August, BlenderNC works in Blender 3.0 Alpha (Hash: b42354672e80):
<img width="507" alt="Screen Shot 2021-08-31 at 2 46 27 pm" src="https://user-images.githubusercontent.com/9144063/131443532-7d112a74-e6b2-43a8-a182-691f5c1d7294.png">

**Comment by josuemtzmo** [comment]
Blender works in the new release of blender, Blender 3.0.0

![Screen Shot 2021-12-10 at 4 32 37 pm](https://user-images.githubusercontent.com/9144063/145599540-056ea960-5ede-4852-8381-a2da0bc99b62.png)

**Comment by almaniac** [comment]
I'm trying to install blendernc for the first time in Blender 3.3.1.  I follow the instructions from here: 
https://blendernc.readthedocs.io/en/latest/

As soon as I attempt to enable the addon Blender crashes.

**Comment by josuemtzmo** [comment]
> Hi @josuemtzmo . First of all thanks a lot for this nice project! I am absolute zero in blender, and try to blindly follow tutorial for simple animation (https://blendernc.readthedocs.io/en/latest/examples/simple_animation.html) As a result I get the following very low resolution image, and animation does not seem to work (although at this resolution it seems to be hard to say for sure :)) ![blender_nc_blender_3](https://user-images.githubusercontent.com/3407313/178820633-4f44c5fe-715f-43d1-884d-d68f4ab4f2ae.png)
> 
> Blender version: `Version 3.2.1 (3.2.1 2022-07-06)`
> 
> Is there anything that I can do to get to the resolution you have in your images? :) Please let me know if you prefer it to be a separate issue.

Hi @koldunovn, I missed completely this comment. It seems to me that the issue had to do with the resolution of the sphere, rather than with the image generation of BlenderNC. Hope this helps, despite the reply being super late.
