### ISSUE TITLE
Unable to load any file

### ISSUE THREAD

**Issue by orioltinto** [blendernc/blendernc#17]
When trying to load a file it fails, looking at the console the error is:

`"File doesn't exist:"`

Digging in the reasons I see that the problem happens in the operator **Import_OT_mfnetCDF**.
In my system, these two lines doesn't work properly.
```
split_path = self.properties.filepath.split('/')[0:-1]
fdir = ('/'.join(str(dir) for dir in split_path))
```

Using dirname from os.path this works properly.

```
fdir = dirname(self.properties.filepath)
```

I think that this approach is safer and more portable.

**Comment by josuemtzmo** [comment]
Excellent solution!!!
