### ISSUE TITLE
New dependencies

### ISSUE THREAD

**Issue by orioltinto** [blendernc/blendernc#18]
It seems that there are new dependencies that were not reported:
- Unable to activate blenderNC without previously installing PIL.
- Unable to load file due to dask not found.

**Comment by orioltinto** [comment]
Also:
`ModuleNotFoundError: No module named 'tlz'`

**Comment by josuemtzmo** [comment]
I've removed PIL as a requirement as it doesn't contribute to the addon, except for displaying an icon in really particular cases. **Dask** will be a requirement for further development as support for clusters will be added in the following iterations.
