### ISSUE TITLE
Error handling clauses in check_netcdf are too vague

### ISSUE THREAD

**Issue by orioltinto** [blendernc/blendernc#19]
I'm obtaining a `ValueError File isn't a netCDF:` when the file is actually a netCDF.

Loking at the reasons I found that the function check_netcdf has a except clause that is too vague:
```
                try:
                    self.load_netcdf()
                except:
                    raise ValueError("File isn't a netCDF:",self.file_path)
```
It should contain only the kind of error that is known that can happen, because otherwise it happens like now that the error message is wrong.

**Comment by josuemtzmo** [comment]
Can you please provide me with an example of the dataset (i.e. filename, netCDF classic vs netCDF4 and structure). I haven't been able to reproduce this error, as if the file is a supported xarray netCDF, it should be loaded with any issue.

**Comment by orioltinto** [comment]
The root of the problem was a Module Import Error due to dask not being installed.
What I'm saying here is that if what we are trying to handle a specific error (i.e. `RuntimeError: NetCDF: file not found.`) then you should put this in the except clause:
```
try:
   ...
except RuntimeError:
   ...
```

Otherwise it can misguide the user if the reason for an exception happening is not that the file isn't a netCDF.
