### ISSUE TITLE
AttributeError: 'Context' object has no attribute 'active_node' when trying to load file from panel

### ISSUE THREAD

**Issue by orioltinto** [blendernc/blendernc#20]
Once dask was installed, when trying to load a file it fails with the message:
`AttributeError: 'Context' object has no attribute 'active_node'`

It happens in this line from **python_functions.py**:
```
context.active_node.blendernc_file = bpy.context.scene.blendernc_file
```

**Comment by josuemtzmo** [comment]
Master has this issue:

https://github.com/blendernc/blendernc/blob/c2fb5ed2ead934d721ef1bf9e6d6e6b5aac82d51/blendernc/python_functions.py#L301-L313

However, this has been deprecated in the `dev` branch in favor of:

https://github.com/blendernc/blendernc/blob/a3342f55025abb3c8dd58db9b2e09ebf0f48227f/blendernc/python_functions.py#L579-L585

**Comment by josuemtzmo** [comment]
Please make sure that you are testing the `dev` branch.
