### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by orioltinto** [blendernc/blendernc#21]
Loading a file from the BlenderNC node-tree and trying to reproduce the same example that I've been extensively using in the past the performance is much slower than what was before and it takes more than 15 seconds to load a single frame. I achieved more than 24fps with it so the slowdown is O(100).

**Comment by josuemtzmo** [comment]
Wow, I've lost performance, but it's in the O(2). I will explore this issue in the next couple of days. Can you provide me some information on the system?

**Comment by josuemtzmo** [comment]
So far the only idea I have for such performance lost is that the netCDF range is been computed at each frame. Could you please test if `update_range` is getting updated, in other words:
```
var_metadata['max_value']==None
var_metadata['min_value']==None
```
Refer to lines: 
https://github.com/blendernc/blendernc/blob/a3342f55025abb3c8dd58db9b2e09ebf0f48227f/blendernc/python_functions.py#L249

and

https://github.com/blendernc/blendernc/blob/a3342f55025abb3c8dd58db9b2e09ebf0f48227f/blendernc/python_functions.py#L153-L154

**Comment by josuemtzmo** [comment]
#14 Closes this issue. Additionally, animated text performance has been solved accordingly with: 
[blender.stackexchange.com](https://blender.stackexchange.com/questions/186617/animated-text-body-drops-playback-fps-by-half)
