### ISSUE TITLE
NetCDF data image loading but not appearing on plane 'ValueError'

### ISSUE THREAD

**Issue by JoshuaB-L** [blendernc/blendernc#22]
Hi Josué,

First of all I just want to thank you for providing the BlenderNC addon for blender.
This is a very exciting development! ;)

I managed to install BlenderNC with all dependencies successfully and the gebco_2020_netcdf data set is loading successfully.

I'm having issues with loading a personal NetCDF4 file in BlenderNC.

It seems that a BlenderNC is looking for a value that is not present in the NetCDF4 file.

Here is an example of the error: 

![2020-10-19_BlenderNC_no_netcdf_data_image_JBL](https://user-images.githubusercontent.com/40243938/96452702-b11ecc00-1219-11eb-815f-d85bf322b740.png)

![2020-10-19_BlenderNC_SelectVariable_No_image_JBL](https://user-images.githubusercontent.com/40243938/96453704-25a63a80-121b-11eb-92da-8496ace1fa6d.png)

<img width="167" alt="2020-10-19_BlenderNC_SelectVariable_JBL" src="https://user-images.githubusercontent.com/40243938/96453744-3191fc80-121b-11eb-9148-cafc48b83ba3.png">

Here is the error from the Blender Python console:

``Traceback (most recent call last):
  File "C:\Users\JBL\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendernc\blendernc\decorators.py", line 39, in wrapper_update
    return func(node)
  File "C:\Users\JBL\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendernc\blendernc\nodes\grid\BlenderNC_NT_resolution.py", line 71, in update
    self.blendernc_dict[self.blendernc_dataset_identifier]['Dataset'] = netcdf_values(dataset,var_name,self.blendernc_resolution)
  File "C:\Users\JBL\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendernc\blendernc\python_functions.py", line 608, in netcdf_values
    variable_res = variable.isel(dict_var_shape).to_dataset()
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\site-packages\xarray\core\dataarray.py", line 1047, in isel
    variable = self._variable.isel(indexers, missing_dims=missing_dims)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\site-packages\xarray\core\variable.py", line 1115, in isel
    indexers = drop_dims_from_indexers(indexers, self.dims, missing_dims)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\site-packages\xarray\core\utils.py", line 768, in drop_dims_from_indexers
    f"dimensions {invalid} do not exist. Expected one or more of {dims}"
ValueError: dimensions {'E_UTM', 'lon', 'N_UTM', 'lat'} do not exist. Expected one or more of ('y', 'x')

location: C:\Users\JBL\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendernc\blendernc\operators.py:94

bpy.ops.blendernc.ncload_sui(file_path="D:\\Downloads\\static_driver_example.nc")
bpy.ops.material.new()
bpy.ops.blendernc.apply_material()
bpy.context.area.ui_type = 'BlenderNC'
bpy.context.area.ui_type = 'BlenderNC'
bpy.context.space_data.shading.type = `'RENDERED'`

Here is the NetCDF4 file I'm using: 
[static_driver_example.zip](https://github.com/blendernc/blendernc/files/5401901/static_driver_example.zip)

Here is the file loaded in Paraview using the NetCDF Reader plugin to give you an example of how the image should look:
![2020-10-19_ParaView_NetCDF-Reader_2d_buildings_JBL](https://user-images.githubusercontent.com/40243938/96454704-8bdf8d00-121c-11eb-89e6-34ea7acb5cba.png)

Maybe you could try loading the file to see what the error is?

I appreciate the help if you can spare the time ;)

Best 

Josh

**Comment by josuemtzmo** [comment]
Hello Joshua,

Thanks for reporting this bug. I found some issues with the current version of BlenderNC, for the record:
1. Applying the material if the object has already been selected. 
2. Use dimensions instead of coordinates to define resolution. 
3. `nans` in dataset will create an empty displacement, thus by default nans are replaced with zeros (TO DO: Create node to preserve `nans` or remove `nans`).

Se attached images of the displace city:
<img width="1920" alt="Screen Shot 2020-10-20 at 8 56 13 pm" src="https://user-images.githubusercontent.com/9144063/96572805-08579600-1319-11eb-9acc-f135fa25e4db.png">

![city](https://user-images.githubusercontent.com/9144063/96572737-eeb64e80-1318-11eb-9f6f-6994aec2f80d.png)

**Comment by josuemtzmo** [comment]
I've push the changes to master, pleas let me know if you have any additional issue.

**Comment by JoshuaB-L** [comment]
Hi Josué,

Thanks for fixing the bug! The script runs pretty well with this data set now.
It took a little while to figure out how to displace the mesh with the height info in the .nc file.
Turns out you need to add a sub surface and displacement modifier, then subdivide the mesh plane around 100 time to achieve the correct resolution on the mesh.

I think it would be great if we could start making video tutorials on various workflows for NetCDF data analysis.
I think this would help BlenderNC users get to grips much faster with the addon.

Here is a render I made with the .nc file I sent you showing building heights ;)
![2020-10-22_BlenderNC_Static-Driver-Night-Time_02_JBL](https://user-images.githubusercontent.com/40243938/96901089-1af5da80-1493-11eb-8d24-69ca67d7da89.png)

Thanks again!

Josh

**Comment by josuemtzmo** [comment]
Hello Josh,

It looks incredible!! I'm glad you are interested in `BlenderNC`. I am looking forward to hear and see more things like this one!!

Josué
