### ISSUE TITLE
buildernc installation CMake Error: The source directory does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by ElMiguelNarvaez** [blendernc/blendernc#23]
Hi, 
I'm installing **blenderNC** in a Blender 2.92.0 Alpha, in a OS Microsoft Windows 10.

I built blender in Windows following the instructions by https://wiki.blender.org/wiki/Building_Blender/Windows and there was no complication.

Now following the **blendernc** installation instructions, when I arrived to this line:
`cmake -DPYTHON_VERSION=3.7  -DPYTHON_ROOT_DIR=~/path/to/python/root ../blender`

I got the next issue:

```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
```

```
CMake Error: The source directory "C:/Users/Miguel/blender-git/build_windows_x64_vc16_Release" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
How can I solve this?

**Comment by ElMiguelNarvaez** [comment]
I fixit deleting the file **CMakeCache.txt**, and creating a folder out of the builder folder (\build_windows_x64_vc16_Release ), Finally the line was executed without issues .
Then I ran the **Blender.sln** since Visual Studio 2019.

But still the blendernc is not installed...

**Comment by josuemtzmo** [comment]
Thanks for raising this issue!! I've added some documentation on how to install the add on. Previously, the documentation only included how to install the required packages in Blender.

**Comment by ElMiguelNarvaez** [comment]
> Thanks for raising this issue!! I've added some documentation on how to install the add on. Previously, the documentation only included how to install the required packages in Blender.

Hi Josué thank you,

I just installed the blendernc-master.zip downloaded from [Add docs on how to install the blendernc addon #24](https://github.com/blendernc/blendernc/pull/24/commits/fa5d7d6f8f0d9e5bf290b2ed1a01c137fc0973af) 

It appears on the add-ons window as _Generic: BlenderNC_ with an advertence icon in front.

When I try to check the box next to _Generic: BlenderNC_ ,  I got the next issue: 

`Traceback (most recent call last):
  File "C:\Users\Miguel\blender-git\build_windows_x64_vc16_Release\bin\Debug\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Miguel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blendernc-master\__init__.py", line 25, in <module>
    from . blendernc.blendernc import registerBlenderNC, unregisterBlenderNC
  File "C:\Users\Miguel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blendernc-master\blendernc\blendernc.py", line 7, in <module>
    from blendernc.blendernc.panels import BlenderNC_UI_PT_3dview, BlenderNC_LOAD_OT_On, \
ModuleNotFoundError: No module named 'blendernc'
`

I already have installed the required packages, and I compiled Blender in my OS Windows 10, but still I can't enable the blendernc add-on...

Thanks in advance!

**Comment by josuemtzmo** [comment]
@orioltinto  Have you had any issues installing the addon?

**Comment by josuemtzmo** [comment]
There were several issues installing BlenderNC using `zip` mode. 

The import of blendernc was replace from a module like import ( i.e. user was expected to install the module as a python package in Blender, import blendernc.blendernc ) to a local import ( import . blendernc ).

**Comment by josuemtzmo** [comment]
I'm not sure why are you getting that error, could you try again reinstalling xarray and all the other python modules:
```
cwd C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin
python.exe -m pip install numpy
python.exe -m pip install xarray
python.exe -m pip install xgcm 
python.exe -m pip install cmocean
python.exe -m pip install matplotlib
```
