### ISSUE TITLE
Select Axis Missing

### ISSUE THREAD

**Issue by JoshuaB-L** [blendernc/blendernc#25]
Hi Josué,

So far, your BlenderNC plugin has helped tremendously with my research and data analysis projects!

I'm having issues selecting a new depth in an axis for example;

I load the NetCDF file then select a variable, then drop I dimension. Once I've dropped the y axis then I will be cutting through the X axis but there is no way to select specific depth in meters in that data set.

Please see my example below:

![2020-10-19_BlenderNC_Select_Axis_Missing_000_JBL](https://user-images.githubusercontent.com/40243938/100100504-358bec80-2e61-11eb-99ca-252f42a27ebb.png)

I have managed to make an animation as shown below but I would like to choose another slice location in either x, y, and z axis:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/40243938/100101144-26f20500-2e62-11eb-8114-40015e46cd57.gif)

I would very much appreciate your help on this issue.

Look forward to your reply,

Joshua

**Comment by josuemtzmo** [comment]
Thanks @JoshuaB-L, The animation looks great!! I love it, could I add it to the documentation of blenderNC? if so, could you please write a couple of sentences explaining what it is?

I will implement the axis selection and slicing in the next couple of days.

**Comment by JoshuaB-L** [comment]
Thanks @josuemtzmo for your kind feedback! Yes you can add the animation to the documentation of BlenderNC. Below you can find a description. Let me know if you have further questions.

**Description**

The animation shows **equivalent potential temperature** (theta-e) of a diabetic process - air moving across a warming urban surface from 10-11:00am on the 16.07.2018 at Potsdamer Platz, Berlin. The wind speed is 7.2 km/ h considered a factor of 2 on the Beaufort Scale (‘Light breeze’). Convection of the rising air parcels is clearly visible from the ground and building surfaces. Heat transfer occurs due the mixing of warm air (at ground level z0) and cool air (above the building canopy), caused by the turbulent rising eddies. Thus, the ambient air temperature of the urban environment rises. The simulation model used is PALM in LES mode. More information can be found here: https://palm.muk.uni-hannover.de/trac/wiki/doc/tut/palm.

**Comment by josuemtzmo** [comment]
Hello @JoshuaB-L, I've implemented the axis selection and time selection you mentioned. I've tested some experiments but I expect some bugs may appear with usage. I will keep testing before merging to master, so please download and install the [zip](https://github.com/blendernc/blendernc/archive/dev.zip) from [dev](https://github.com/blendernc/blendernc/tree/dev). 
Please let me know if you find any issue :).

**Comment by JoshuaB-L** [comment]
Hey @josuemtzmo, Thank you very much for updating the BlenderNC with 'Select Axis'. This is a huge help ;).

I've attached a short mp4 to demonstrate it working on my dataset: [2020-12-01_BLenderNC_Select_Axis_Test_000_JBL.zip](https://github.com/blendernc/blendernc/files/5624146/2020-12-01_BLenderNC_Select_Axis_Test_000_JBL.zip)

Do you think it will be possible to add particle tracer to represent 3D wind flow fields?

Something like this: (https://www.instagram.com/p/B_0SmfhIXO6/) or this https://www.instagram.com/p/CAme34rIV6r/

I made these in ParaView using the 'stream tracer' filter. It'S a super useful tool.

I was thinking it could also be linked to Blenders particle system to render flowing particles?

Look forward to the future developments ands keep up the great work! ;)

**Comment by josuemtzmo** [comment]
Wow, thanks for attaching the short mp4, it looks great. I've created a new issue-improvement to add support for flow fields. I suspect this implementation will take some time, as I would like to support 3D flow fields instead of only 2D. If you have any idea or suggestion, please post it in the issue #31
