### ISSUE TITLE
Problems with dependencies running on Windows

### ISSUE THREAD

**Issue by orioltinto** [blendernc/blendernc#3]
After installing matplotlib and cmocean I can not load the Addon on windows since its complaining about tkinter, which I've been unable to install.

**Comment by josuemtzmo** [comment]
Could you provide more information, I'm unable to reproduce the issue.

**Comment by josuemtzmo** [comment]
This issue has been solved, thanks to @orioltinto, who suggested to switch the backend of `matplotlib`:

```
import matplotlib
        matplotlib.use('Agg')
```
in [blendernc/nodes/utils_colorramp.py](https://github.com/blendernc/blendernc/blob/d9b0e3f19a487b21c71cef4eed2615dc988a87cb/nodes/utils_colorramp.py#L16)
