### ISSUE TITLE
Add PyCQA tools via CI

### ISSUE THREAD

**Issue by whatnick** [blendernc/blendernc#32]
Implement GHA for PyCQA tools like :
- black
- isort
- pyupgrade
....

Or use [shed](https://github.com/Zac-HD/shed/)

**Comment by josuemtzmo** [comment]
#38 Implemented code style **black** (PR test) and implemented CI on Travis using Docker. Future versions will implement GitHub actions with `isort` and `pyupgrade` (PR test). It may be also useful for future development to include a `.pre-commit-config.yaml` file.
