### ISSUE TITLE
Import other file formats (cgrib and zar)

### ISSUE THREAD

**Issue by josuemtzmo** [blendernc/blendernc#43]
`xarray` has the capacity to import different file formats such as `cgrib` and `zarr`:

- [x] cgrib file implementation 
- [ ] zar file implementation 

Possible the best location to implement this feature is: 

https://github.com/blendernc/blendernc/blob/82c0c6d975bda0ee9da755b0a04ff466383dba6f/blendernc/python_functions.py#L890-L894

Implementation could read metadata and decide wich engine to use in `xr.open_mfdataset`:
```({"netcdf4", "scipy", "pydap", "h5netcdf", "pynio", "cfgrib", "zarr"})```
More info at:
http://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html#xarray.open_mfdataset

**Comment by whatnick** [comment]
There is currently a lot of places in the BlenderNC codebase with hardcoded reference to NetCDF. We should prioritize gradually replacing them to more format agnostic wording. Something like "Spatio-Temporal Datacube" seems more accurate and there is a broad consensus on this data model.
![image](https://user-images.githubusercontent.com/491396/120085524-3eb18b00-c11c-11eb-8d12-121ebf0a8d06.png)

**Comment by whatnick** [comment]
Remaining tasks : 

- [ ] Update wording in a lot of places to indicate more generic climate datacube support
- [ ] Update UI to support multiple extensions
- [ ] Update install mechanism via requirements to ensure [ecCodes](https://github.com/ecmwf/eccodes) is installed alongside Python components.
- [ ] Update docs to demonstrate support for GRIB format particularly those generated by ECMWF.

**Comment by StephanSiemen** [comment]
Before installing the eccodes C library, we could try the more lightweight Python-only pyeccodes package. It does not have as much functionality but might cover all needs here and would just mean one more pip package rather a binary dependency! Let's discuss in the next call (which we should have soon!)

**Comment by josuemtzmo** [comment]
Unfortunately, BlenderNC uses the `xarray` API to request and access data, thus we should include eccodes within blenderNC. I haven't been able to test blenderNC within an environment where eccodes has been compiled. Do you have any suggestions?

**Comment by whatnick** [comment]
I will compile eccodes in the docker container in CI or even create a BelnderNC docker container from the Nytimes blender container.
