### ISSUE TITLE
How to test BlenderNC?

### ISSUE THREAD

**Issue by josuemtzmo** [blendernc/blendernc#47]

**Comment by whatnick** [comment]
Here are my testing suggestions :
- [ ] Unit tests using pytests for all non-interactive sections like data loading etc.
- [ ] Integrations tests using a headless blender session + data + render calls to capture functionality
- [ ] Coverage to measure completeness of testing

**Comment by josuemtzmo** [comment]
#74 Implemented `Blender_NC_tutorial` to load `xarray.tutorial.load_dataset` examples. In adition, `blendernc/test/test_default.py` can be executed to generate an image. The image can be generated by running (headless blender):

Blender --background --python ./test/test_default.py 

WIP:

- [ ] implement pytest to assert if the file is created after running the code.

**Comment by josuemtzmo** [comment]
#74 implements a test suit and coverage. I will leave this issue open to collect ideas on how to improve test and support in different blender versions. 

- [ ]  @whatnick suggested using GitHub matrix test to check using different blender versions.
