### ISSUE TITLE
Create a repository under ESoWC space GitHub.

### ISSUE THREAD

**Issue by josuemtzmo** [blendernc/blendernc#51]
> This issue includes a draft of the README.md to connect the ESOWC Challenge 31 with the main repository of BlenderNC: 

# ECMWF Summer of Weather Code 2021 - BlenderNC

This repository connects the development of BlenderNC to the ECMWF summer of Weather Code 2021. To know more about the development, go to the main repository of [BlenderNC](https://github.com/blendernc/blendernc). For specific development under ESOWC you can filter the pull request and issues with the label 'ESOWC - 2021'

## What is BlenderNC? 

Is an open-source Blender add-on developed to increase reachability of real-time visualizations and animations of scientific data to the scientific community, with a focus on climate sciences. In addition, BlenderNC attempts to simplify and intuitively produce quality 3D visualizations. 

### Challenge 31 main goals include:

1. Document the whole workflow end-to-end with BlenderNC documentation tools.
2. Support GRIB is a valid file format for BlendeNC at UI level
3. Load GRIB files successfully into memory as Xarray data types within the Blender python runtime
4. Render as blender 3D objects and where relevant as procedural textures the data contained in the Grib files within the Blender UI
5. Create interesting animations and tutorials using ECMWF forecast data. 

## Team 
- Tishampati Dhar @whatnick 
- Gichini Ngaruiya
- Josue Martinez Moreno @josuemtzmo

**Comment by josuemtzmo** [comment]
Also, I would like to add a section in the main BlenderS README.md, acknowledging ECMWF, do you have any suggestions? My current idea is to add a supporters or ECMWF section, where we say something like: 

> ECMWF has granted support to further develop BlenderNC as part of the ECMWF summer of Weather Code 2021, an open-source summer coding program dedicated to innovative open-source software and visualization of weather data.

**Comment by StephanSiemen** [comment]
Thanks @josuemtzmo , I am already started working on some text and the logos we can put. I get back to you :-)

**Comment by josuemtzmo** [comment]
@StephanSiemen, It will be great if we could also add something in the ReadTheDocs after the Community section: 

https://blendernc.readthedocs.io/en/docs/index.html

What do you think?

**Comment by josuemtzmo** [comment]
#85 Adds reference within the BlenderNC repository. The proposed README.md will be added to a repository within the ESOWC organisation.

**Comment by josuemtzmo** [comment]
A new repository has been created within the ESoWC organisation. For changes in the reference between ESoWC and BlenderNC, submit a new issue in the repository:

https://github.com/esowc/BlenderNC_ESoWC_2021
