### ISSUE TITLE
Errors with Blender 2.93 when loading NetCDF

### ISSUE THREAD

**Issue by StephanSiemen** [blendernc/blendernc#52]
Hi,

after updating to Blender 2.93, I get the error below when trying to load a NetCDF file. The same file with Blender 2.92 on the same machine loads successfully. Please note Blender 2.93 is now using Python 3.9 (instead of 3.7 in Blender 2.92).

Any ideas?  

```python
Python: Traceback (most recent call last):
  File "/Users/stephan/Library/Application Support/Blender/2.93/scripts/addons/blendernc-master/blendernc/operators.py", line 387, in execute
    fdir = dirname(self.properties.filepath)
AttributeError: 'BLENDERNC_OT_import_mfnetcdf' object has no attribute 'filepath'

location: <unknown location>:-1
```

BTW, Blender 2.93 also offers the first time a arm64 version for MacOS M1 machines. Unfortunately, BlenderNC can not be used with this version, because the dependencies (xarray & SciPy) are not available on arm64 :-(

**Comment by StephanSiemen** [comment]
Hi @josuemtzmo . Can confirm that this issue is fixed with #54 :-) Thanks for the fast turnaround!

**Comment by josuemtzmo** [comment]
I've tested in my end and it works, I will reopen it, just in case you find any issue.

**Comment by StephanSiemen** [comment]
All my test show that BlenderNC works now well with Blender 2.93. Close issue. Thanks
